### ISSUE TITLE
Difference between dmesg

### ISSUE THREAD

**Issue by pickfire** [polyverse/rmesg#1]
Is there any other difference compared to dmesg other than being rust port?

**Comment by archisgore** [comment]
Not particularly at a high semantic level - `dmesg` and `rmesg` read kernel log buffers. Implementation-wise two notable differences:
1. rmesg does not yet read `/dev/kmsg` when available. It always makes a `klogctl` call. Some day I'll implement `/dev/kmsg` reader.

2. The "Follow" logic: `dmesg` has follow logic on later kernels because they support `/dev/kmsg` (which can be tailed) and/or unique sequence numbers for each entry. This allows eliminating duplicates when polling. rmesg implements follow using timestamps (which I found to be available on as old as Red Hat 6 kernels.)

But finally - dmesg didn't export an API. rmesg can be imported as a crate and used to programmatically tail logs - this can be very useful for building other tools.

For example:
https://github.com/polyverse/zerotect/blob/master/src/monitor/rmesg_reader.rs#L55

**Comment by pickfire** [comment]
> But finally - dmesg didn't export an API. rmesg can be imported as a crate and used to programmatically tail logs - this can be very useful for building other tools.

Yes, that is something dmesg cannot do. Interesting other than the technical differences.

But is there like sort of performance improvements like what other rust ripoffs provides?

**Comment by archisgore** [comment]
Not really that I know of. I'd imagine it performs a fair bit worse actually - but that's my implementation designed to make it work, and make it beautiful.

**Comment by archisgore** [comment]
I've now updated rmesg to read the /dev/kmsg file as well and provide a sync/async API. Just FYI. When it falls back to the klogctl it still polls (since the fundamental syscall is a single-shot call and has no async ability.)
